import Head from "next/head";
import { Inter } from "@next/font/google";
import { SimpleGrid, Container, Center } from "@chakra-ui/react";
import fsPromises from 'fs/promises';
import path from 'path'
import CardItem from "../components/CardItem";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  
  const [itemData , setItemData] = useState(props.cardData)
	return (
		<>
			<Head>
				<title>ENOCH Interview Task</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="grid-area">
					<Center h={{ base: "100%", md: "100%", xl: "100vh" }} color="white">
						<Container maxW="7xl" p="6">
							<SimpleGrid
								columns={{
                  base: '1', // 0-48em
                  md: '2', // 48em-80em,
                  xl: '3', // 80em+
                }} spacing={10}
							>
                {
                  itemData.map( item => <CardItem
                  key={item.id}
                  item={item}
                  >

                  </CardItem>)
                }
								
							</SimpleGrid>
						</Container>
					</Center>
				</div>
			</main>
		</>
	);
}

export const getStaticProps = async () => {
	const filePath = path.join(process.cwd(), '/json/data.json');
  const res = await fsPromises.readFile(filePath);
	const data = JSON.parse(res);
 
	return {
		props: {
			cardData: data,
		},
	};
};
